### PR TITLE
Added changeModulation

### PR DESCRIPTION
**Pull request by kiseitai3**
changeModulation is a new method to enable OOK modulation after initialization of the modem with beginFSK(). It just writes to the same register as config()/configFSK()

You would set modulation with the MACRO SX127X_MODULATION_OOK for OOK and SX127X_MODULATION_FSK for FSK.

### CODE REVIEW

**Comment by jgromes** [comment]
I would much rather have this as a separate `beginOOK()` method, to distinguish between FSK and OOK mode e.g. bitrate calculation in FSK and OOK. Essentially, we would treat OOK as a separate "modem" on the level of LoRa and FSK modems.

**Comment by kiseitai3** [comment]
Ok. I have a question, does that mean I should submit updates to the other drivers? I know some drivers re-implement/overload the begin methods and that's where the modem gets configured via config<modulation>(). I'll start work on it soon.

**Comment by jgromes** [comment]
The reason for that is that some modules have different parameter ranges, and the begin methods must accommodate that. For example, SX1278 frequency is in range 137 - 525 MHz, but SX1272 in range 868 - 1020 MHz. Anything that is common to all the modules is in base class SX127x. The class hierarchy can be found [here](https://jgromes.github.io/LoRaLib/hierarchy.html).

**Comment by jgromes** [comment]
I read through the datasheets, it looks like there's not that much difference in parameters when using OOK, the biggest ones are:
1. Lower maximum bit rate.
2. Different bit rate calculation.
3. Different shaping.

With that in mind, it's probably not necessary to treat OOK as a separate modem, so here's how I think this should be handled:
1. Add one more parameter to `beginFSK()`, e.g. `enableOOK` and have it default to `false`
2. In `setBitRate` add check to see if OOK is enabled and if so, change the allowed range and bit rate calculation.

**Comment by kiseitai3** [comment]
Excellent! I'll work on it.

**Comment by kiseitai3** [comment]
Give me a couple of days before I can make a pull request. I may not get around to do it today because I will be busy with some anniversary stuff.

**Comment by kiseitai3** [comment]
Closing this pull request in preparation for the new one.

**Pull request closed without merging**
